language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t shobhan/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shobhan/docker-react npm run test